name: Ibiza
favicon: null
layout_spectrum: 0.044315951177850366
typography_spectrum: 0.8688292379956692
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.963693390134722
  lightness: 0.6414644033648074
  saturation: 0.7446310226805508
  rhythmicContrast: 0.7828627782873809
purpose: []
